Repository jaewgwon/wtfru, pull requests merged in 2021-08, with the labels that each got.

#34 feat: Add Vuex for store in location, stauts, session
  frontend/src/store/index.js
  frontend/src/store/location/location.js
  frontend/src/store/session/session.js
  frontend/src/store/status/status.js
Labels: P0

#46 refactor: Downgrade Vue Version
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/store.js
  frontend/src/store/index.js
  frontend/src/views/About.vue
  frontend/src/views/Home.vue
  frontend/yarn.lock
Labels: P0

#43 chore: Add exceptions class for handling custom exceptional cases
  backend/src/main/java/com/wtfru/backend/exception/DataIOException.java
  backend/src/main/java/com/wtfru/backend/exception/ValidationException.java
  backend/src/main/java/com/wtfru/backend/service/StatusService.java
  backend/src/main/java/com/wtfru/backend/service/StatusServiceImpl.java
Labels: enhancement

#27 Issue#17 develop token manager
  backend/build.gradle
  backend/src/main/java/com/wtfru/backend/BackendApplication.java
  backend/src/main/java/com/wtfru/backend/config/MyBatisConfig.java
  backend/src/main/java/com/wtfru/backend/config/SecurityConfig.java
  backend/src/main/java/com/wtfru/backend/controller/SessionController.java
  backend/src/main/java/com/wtfru/backend/dao/SessionDAO.java
  backend/src/main/java/com/wtfru/backend/dto/SessionDTO.java
  backend/src/main/java/com/wtfru/backend/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/com/wtfru/backend/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/wtfru/backend/jwt/JwtFilter.java
  backend/src/main/java/com/wtfru/backend/jwt/JwtSecurityConfig.java
  backend/src/main/java/com/wtfru/backend/service/SessionService.java
  backend/src/main/java/com/wtfru/backend/service/SessionServiceImpl.java
  backend/src/main/java/com/wtfru/backend/service/TokenService.java
  backend/src/main/java/com/wtfru/backend/session/controller/SessionController.java
  backend/src/main/java/com/wtfru/backend/session/dao/SessionDAO.java
  backend/src/main/java/com/wtfru/backend/session/service/SessionServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/sessions.sql
  backend/src/test/java/com/wtfru/backend/session/SessionMockTest.java
  backend/src/test/java/com/wtfru/backend/session/SessionTest.java
Labels: P0

#44 Issue#30 develop status service
  backend/src/main/java/com/wtfru/backend/service/StatusService.java
  backend/src/main/java/com/wtfru/backend/service/StatusServiceImpl.java
  backend/src/test/java/com/wtfru/backend/status/StatusMockTest.java
  backend/src/test/java/com/wtfru/backend/status/StatusTest.java
Labels: P0

#48 chore: Fix inappropriate codes related to import path and exception invocation
  backend/src/main/java/com/wtfru/backend/controller/StatusController.java
  backend/src/main/java/com/wtfru/backend/service/StatusService.java
  backend/src/main/java/com/wtfru/backend/service/StatusServiceImpl.java
  backend/src/test/java/com/wtfru/backend/status/StatusTest.java
Labels: enhancement, P0

#50 feat: Add LocationDTO and fix SessionDTO for location service
  backend/src/main/java/com/wtfru/backend/dto/LocationDTO.java
  backend/src/main/java/com/wtfru/backend/dto/SessionDTO.java
  backend/src/main/resources/sql/locations.sql
  backend/src/main/resources/sql/sessions.sql
Labels: enhancement, P0

#51 feat: Add LocationDAO for location related API
  backend/src/main/java/com/wtfru/backend/dao/LocationDAO.java
Labels: P0

#53 feat: Develop location service for location API
  backend/src/main/java/com/wtfru/backend/service/LocationService.java
  backend/src/main/java/com/wtfru/backend/service/LocationServiceImpl.java
Labels: P0

#59 chore: Relocate resolveToken method from JwtFilter to TokenService
  backend/src/main/java/com/wtfru/backend/jwt/JwtFilter.java
  backend/src/main/java/com/wtfru/backend/service/TokenService.java
Labels: enhancement

#57 chore: Fix attribute of a method in LocationDAO
  backend/src/main/java/com/wtfru/backend/dao/LocationDAO.java
Labels: enhancement

#58 chore: Fix location service attirbute
  backend/src/main/java/com/wtfru/backend/service/LocationService.java
  backend/src/main/java/com/wtfru/backend/service/LocationServiceImpl.java
Labels: enhancement

#63 chore: Fix location service for changed attribution
  backend/src/main/java/com/wtfru/backend/service/LocationService.java
  backend/src/main/java/com/wtfru/backend/service/LocationServiceImpl.java
Labels: enhancement, P0

#61 refactor: Fix TokenService and SessionController for decoding JWT feature
  backend/src/main/java/com/wtfru/backend/controller/SessionController.java
  backend/src/main/java/com/wtfru/backend/service/TokenService.java
Labels: enhancement, P0

#64 style: fix store style
  frontend/src/store/index.js
  frontend/src/store/location/location.js
  frontend/src/store/session/session.js
  frontend/src/store/status/status.js
Labels: P0

#65 style: Fix API Style
  frontend/src/api/index.js
  frontend/src/api/service/service.js
Labels: P0

#67 feat: Build location controller and mock test class
  backend/src/main/java/com/wtfru/backend/controller/LocationController.java
  backend/src/test/java/com/wtfru/backend/location/LocationMockTest.java
Labels: P0

#70 chore: Fix querys and attributes in LocationDAO for implementation of controller
  backend/src/main/java/com/wtfru/backend/dao/LocationDAO.java
  backend/src/main/resources/sql/locations.sql
Labels: enhancement, P0

#71 refactor: Fix attributes and logics in LocationService
  backend/src/main/java/com/wtfru/backend/service/LocationServiceImpl.java
Labels: enhancement, P0

#54 feat: Add MainComponent Button & Layout
  frontend/README.md
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/button/MainButton.vue
  frontend/src/components/grid/MainGrid.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/Main.vue
  frontend/yarn.lock
Labels: P0

#79 Issue#74 fix typos and inappropriate codes
  backend/src/main/java/com/wtfru/backend/controller/StatusController.java
  backend/src/main/java/com/wtfru/backend/dao/LocationDAO.java
  backend/src/main/java/com/wtfru/backend/service/SessionService.java
  backend/src/main/java/com/wtfru/backend/service/SessionServiceImpl.java
Labels: enhancement, P1

#80 chore: Change MainGrid Style
  frontend/src/components/grid/MainGrid.vue
Labels: P3
